/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 model.glb -T --shadows 
Files: model.glb [24.85MB] > /home/dazzell/dazzell/public/models/art/model-transformed.glb [1.22MB] (95%)
Author: Scar56 (https://sketchfab.com/Scar56)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/torsion-pendulum-clock-animation-cb84e55159e545428282d23c3995039d
Title: Torsion Pendulum Clock - Animation
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model({ setActions, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/art/model.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play a specific animation by name
    actions["Animation"].play();

    setActions(actions); // for animaiton sett

    // Optional: Stop the animation when the component unmounts
    // return () => actions['fly'].stop()
  }, [actions]);

  return (
    <group
      ref={group}
      {...props}
      scale={20}
      position={[0, -2, 0]}
      rotation={[0.1, 0, 0]}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Pendule_1" position={[0, 0.123, -0.027]}>
            <mesh
              name="Object_7"
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.Gold}
            />
          </group>
          <group name="Corde_2" position={[0, 0.19, -0.027]}>
            <mesh
              name="Object_9"
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.Gold}
            />
          </group>
          <group name="Barillet_3" position={[0.009, 0.15, 0]}>
            <mesh
              name="Object_11"
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.Gold}
            />
          </group>
          <group name="Engrenage_1_4" position={[-0.007, 0.167, 0]}>
            <mesh
              name="Object_13"
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials.Gold}
            />
          </group>
          <group name="Engrenage_2_5" position={[-0.02, 0.162, 0]}>
            <mesh
              name="Object_15"
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.Gold}
            />
          </group>
          <group name="Engrenage_3_6" position={[-0.014, 0.146, 0]}>
            <mesh
              name="Object_17"
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.Gold}
            />
          </group>
          <group name="Aiguille_Minute_7" position={[0, 0.171, 0]}>
            <mesh
              name="Object_19"
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.Gold}
            />
          </group>
        </group>
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Gold}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Basic_Glass}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/art/model.glb");
export default Model;
